CREATE TABLE LogbookContacts (
    id TEXT PRIMARY KEY,
    uid TEXT REFERENCES UserProfile(id),       -- links to user
    logBookId TEXT REFERENCES LogBook(id),     -- optional: link to a specific logbook entry
    myCallSign TEXT,
    profileCallSign TEXT,
    theirCallsign TEXT,
    callSignSearchIndex TEXT[],
    band TEXT,
    userMode TEXT,
    frequency TEXT,
    rstSent TEXT,
    rstRCVD TEXT,
    power TEXT,
    myRadio TEXT,
    myAntenna TEXT,
    userQth TEXT,
    qth TEXT,
    myCity TEXT,
    myState TEXT,
    myCountry TEXT,
    country TEXT,
    countryCode TEXT,
    flagCode TEXT,
    continent TEXT,
    distance DOUBLE PRECISION,
    time TEXT,
    date DATE,
    timestamp BIGINT,
    contactTimeStamp BIGINT,
    adiFileName TEXT,
    adiImported BOOLEAN,
    lotwImportedOn BIGINT,
    lotwUploadedOn BIGINT,
    qrzImportedOn BIGINT,
    qrzUploadedOn BIGINT,
    nameSearchIndex TEXT[],
    myNameSearchIndex TEXT[],
    myProfilePic TEXT,
    operator TEXT,
    grid TEXT,
    userGrid TEXT,
    errorMessage TEXT,
    notes TEXT,
    active BOOLEAN,
    dxccNumber INTEGER,
    contactString TEXT,
    myName TEXT,
    theirName TEXT,
    theirState TEXT,
    theirCountry TEXT
);